### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [okhiroyuki/zsh-select-history-skim#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by okhiroyuki** [comment]
@unixorn 
thanks!

add now
eb085c6cee18304e13705b0b8edf3aaa59b1d659
